---
- name: Install docker-compose from sources
  block:
    - name: Check current docker-compose version.
      command: "{{ docker_compose_path }} --version"
      register: docker_compose_vsn
      check_mode: false
      changed_when: false
      failed_when: false

    - set_fact:
        docker_compose_current_version: "{{ docker_compose_vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
      when: >
        docker_compose_vsn.stdout is defined
        and (docker_compose_vsn.stdout | length > 0)

    - name: Delete existing docker-compose version if it's different.
      file:
        path: "{{ docker_compose_path }}"
        state: absent
      when: >
        docker_compose_current_version is defined
        and (docker_compose_version | regex_replace('v', '')) not in docker_compose_current_version

    - name: Install Docker Compose (if configured).
      get_url:
        url: "{{ docker_compose_url }}"
        dest: "{{ docker_compose_path }}"
        mode: 0755
      when: >
        (docker_compose_current_version is not defined)
        or (docker_compose_current_version | length == 0)
        or (docker_compose_current_version is version((docker_compose_version | regex_replace('v', '')), '<'))
  when:
    - docker_install_compose_from_source

- name: Install docker-compose from pip
  block:
    - name: Delete existing docker-compose installed from sources
      file:
        path: "{{ docker_compose_path }}"
        state: absent

    - name: Delete default docker-compose package
      package:
        name: "docker-compose"
        state: absent

    - name: Ensure pip installation
      package:
        name: "python3-pip"
        state: present

    - name: Install newer version of pip itself
      pip:
        name: "pip"
        state: latest
        executable: pip3

    - name: Install Docker Compose from pip
      pip:
        name: "docker-compose=={{ docker_compose_version }}"
        state: present
        executable: pip3
  when:
    - docker_install_compose_from_pip

- name: Install docker-compose from packages
  block:
    - name: Delete existing docker-compose installed from sources
      file:
        path: "{{ docker_compose_path }}"
        state: absent

    - name: Install Docker Compose (if configured).
      package:
        name: "docker-compose"
        state: present
  when:
    - not docker_install_compose_from_source
    - not docker_install_compose_from_pip


